name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rhkdguskim/kakaotalk-backend
          stage: main
          yaml: >
            name: kakaotalk-frontend

            app: web

            options:
              nodeversion: "18"
              spa: true
              buildenv:
                - name: REACT_APP_API_HOST
                  value: https://port-0-kakaotalk-backend-eu1k2lllawv5vy.sel3.cloudtype.app
                - name: REACT_APP_OAUTH_REDIRECT_URL
                  value: https://web-kakaotalk-frontend-eu1k2lllawv5vy.sel3.cloudtype.app/oauth
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
